SUBDIRS = src
dist_bin_SCRIPTS = deploy/gsrnd_start.sh deploy/gsrnd_tcpmem_watch.sh deploy/gsrnd_connlimit_reload.sh monitor/heartbeat.sh
EXTRA_DIST = README.md config bootstrap LICENSE ChangeLog deploy/provision.sh deploy/gsrnd.service deploy/gsrn-hb.service deploy/gsrnd-tcpmem.service deploy/gsrnd-connlimit-reload.service
