#! /bin/bash

MIN()
{
	echo $(($1>$2 ? $2 : $1))
}

ERREXIT()
{
	local code
	code="$1"

	[[ $? -ne 0 ]] && code="$?"
	[[ -z $code ]] && code=99

	shift 1
	[[ -n $1 ]] && echo -e >&2 "ERROR: $*"

	exit "$code"
}

XMD5() { md5sum "${1}" 2>/dev/null | cut -f1 -d' '; }

if [[ $# -eq 0 ]]; then
	source "${BASEDIR}/.gsrn_hosts"
	SSH_HOSTS=($(<"${BASEDIR}/.gsrn_ssh"))
else
	HOSTS=("$@")
	SSH_HOSTS=("$@")
fi
