name: Static Build
on: [workflow_dispatch]

permissions:
  contents: write

env:
  OPENSSL_VER: 1.1.1w
  LIBEVENT_VER: 2.1.12-stable
  TAG: v1.0.15
  # TAG: ${{ github.ref == 'ref/heads/main' && 'latest' || github.ref }}

jobs:
  Linux-Cross:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    runs-on: ubuntu-latest
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v7

      - name: Cache SSL + LibEvent
        id: cachessl
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/gsrn-deps
          key: ${{ runner.os }}-muslcc-${{ matrix.arch }}-openssl-${{ env.OPENSSL_VER }}-libevent-${{ env.LIBEVENT_VER }}-v2

      - name: Build static binaries
        env:
          CACHE_HIT: ${{ steps.cachessl.outputs.cache-hit }}
        run: |
          mkdir -p "$RUNNER_TEMP/gsrn-deps"
          docker run --rm --platform linux/amd64 -e OPENSSL_VER -e LIBEVENT_VER -e ARCH -e CACHE_HIT -v "$GITHUB_WORKSPACE:/work" -v "$RUNNER_TEMP/gsrn-deps:/opt" -w /work -i "muslcc/x86_64:$ARCH-linux-musl" sh -e <<'BUILD'
          apk add --update --no-cache --no-progress tar git autoconf automake make curl bsd-compat-headers file

          if [ "$CACHE_HIT" != true ]; then
            curl -SsfL "https://www.openssl.org/source/openssl-$OPENSSL_VER.tar.gz" | tar -xzf - -C /tmp
            (
              cd "/tmp/openssl-$OPENSSL_VER"
              ./Configure --prefix=/opt no-tests no-dso no-threads no-shared linux-generic64
              make install_sw
            )
            curl -SsfL "https://github.com/libevent/libevent/releases/download/release-$LIBEVENT_VER/libevent-$LIBEVENT_VER.tar.gz" | tar -xzf - -C /tmp
            (
              cd "/tmp/libevent-$LIBEVENT_VER"
              PKG_CONFIG_PATH=/opt/lib/pkgconfig CFLAGS="-I/opt/include" LDFLAGS="-L/opt/lib" ./configure --prefix=/opt --enable-static --host="$ARCH"
              make install
            )
            rm -rf "/tmp/openssl-$OPENSSL_VER" "/tmp/libevent-$LIBEVENT_VER" /opt/bin/openssl /opt/bin/c_rehash
          fi

          git clone -b beta --depth 1 --single-branch https://github.com/hackerschoice/gsocket.git
          (
            cd gsocket
            ./bootstrap
            ./configure --prefix=/opt --enable-realprefix=/usr --enable-static --host="$ARCH"
            make all
          )
          ./bootstrap
          LDFLAGS="-L/opt/lib" LIBS="-lssl -lcrypto" ./configure --prefix=/opt --enable-static --host="$ARCH"
          make
          file src/gsrnd src/gsrn_cli
          mv src/gsrnd "gsrnd-linux-$ARCH"
          mv src/gsrn_cli "gsrn_cli-linux-$ARCH"
          BUILD

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: gsrn*-linux-${{ matrix.arch }}
          overwrite: true
          tag: ${{ env.TAG }}
